<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Reliv\AxosoftApi\Module'                               => __DIR__ . '/Module.php',
    'Reliv\AxosoftApi\Controller\IndexController'           => __DIR__ . '/src/AxosoftApi/Controller/IndexController.php',
    'Reliv\AxosoftApi\Factory\AxosoftApiServiceFactory'     => __DIR__ . '/src/AxosoftApi/Factory/AxosoftApiServiceFactory.php',
    'Reliv\AxosoftApi\Factory\GuzzleHttpClientFactory'      => __DIR__ . '/src/AxosoftApi/Factory/GuzzleHttpClientFactory.php',
    'Reliv\AxosoftApi\Factory\UsernamePasswordGrantFactory' => __DIR__ . '/src/AxosoftApi/Factory/UsernamePasswordGrantFactory.php',
    'Reliv\AxosoftApi\Model\AbstractApiError'               => __DIR__ . '/src/AxosoftApi/Model/AbstractApiError.php',
    'Reliv\AxosoftApi\Model\AbstractApiRequest'             => __DIR__ . '/src/AxosoftApi/Model/AbstractApiRequest.php',
    'Reliv\AxosoftApi\Model\AbstractApiResponse'            => __DIR__ . '/src/AxosoftApi/Model/AbstractApiResponse.php',
    'Reliv\AxosoftApi\Model\ApiRequestInterface'            => __DIR__ . '/src/AxosoftApi/Model/ApiRequestInterface.php',
    'Reliv\AxosoftApi\Model\GenericApiError'                => __DIR__ . '/src/AxosoftApi/Model/GenericApiError.php',
    'Reliv\AxosoftApi\Model\GenericApiRequest'              => __DIR__ . '/src/AxosoftApi/Model/GenericApiRequest.php',
    'Reliv\AxosoftApi\Model\GenericApiResponse'             => __DIR__ . '/src/AxosoftApi/Model/GenericApiResponse.php',
    'Reliv\AxosoftApi\Service\AxosoftApi'                   => __DIR__ . '/src/AxosoftApi/Service/AxosoftApi.php',
    'Reliv\AxosoftApi\V5\UsernamePasswordGrant\ApiError'    => __DIR__ . '/src/AxosoftApi/V5/UsernamePasswordGrant/ApiError.php',
    'Reliv\AxosoftApi\V5\UsernamePasswordGrant\ApiRequest'  => __DIR__ . '/src/AxosoftApi/V5/UsernamePasswordGrant/ApiRequest.php',
    'Reliv\AxosoftApi\V5\UsernamePasswordGrant\ApiResponse' => __DIR__ . '/src/AxosoftApi/V5/UsernamePasswordGrant/ApiResponse.php',
);
